We classificeren de iris data met behulp van een neuraal netwerk.

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

import warnings
warnings.filterwarnings('ignore')

Laad de dataset en maak een feature matrix X en een target vector y.

In [2]:
iris = sns.load_dataset('iris')

# we gebruiken .values om een Numpy array te krijgen in plaats van een Pandas DataFrame
X_iris = iris.drop('species', axis=1).values 
y_iris = iris['species'].values

In [3]:
y_iris = y_iris.reshape(-1, 1) # maak een array van array's, dit is nodig voor de volgende stap
print(y_iris[:10])

[['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']]


Een neuraal netwerk kan niet omgaan met categorische labels zoals de namen van de planten, maar heeft getallen als uitput nodig. We hebben hier drie klassen (setosa, versicolor, virginica) daarom maken we een target vector met per label drie waarden. Een 1 voor de eerste waarde correspondeert met 'setosa', een 1 voor de 2e waade met 'versicolor' en een 1 voor de derde waarde met 'virginica'.
Doe dit met behulp van het OneHotEncoder object uit sklearn. Hint: dit object werkt net als CountVectorizer maar dan op de labels in de target vector.

In [4]:
from sklearn.preprocessing import OneHotEncoder

# One Hot encode de labels
encoder = OneHotEncoder(sparse=False)
y_encoded = encoder.fit_transform(y_iris)

print(y_encoded[:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


We hebben de data nu in een geschikt formaat. Splits de data in `X_iris` en `y_encoded` in training en test data.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X_iris, y_encoded, test_size = 0.2, random_state = 42)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 3)
(30, 3)


Maak een eenvoudig neuraal netwerk met 3 lagen, waarin elke neuron in een laag met elk neuron in de vorige laag verbonden is ('Dense'). Voeg voor de eeste laag een parameter input_shape toe die aangeeft hoeveel features een element in 'X' heeft. Het aantal neuronen in de laaste laag is gelijk aan het aantal waarden in een label in y.

In [6]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(4, input_shape = (4,), activation = 'relu'))
model.add(Dense(3, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

Using TensorFlow backend.


Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Compileer en bekijk het netwerk door onderstaande code te runnen.

In [7]:
from keras.optimizers import Adam

model.compile(Adam(lr=0.01),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 12        
Total params: 47
Trainable params: 47
Non-trainable params: 0
_________________________________________________________________


Nu kunnen we ons model trainen met behulp van de `fit` methode.

In [8]:
model.fit(X_train, y_train, epochs = 25, batch_size = 5)


Epoch 1/25
120/120 [==============================] - 0s 1ms/step - loss: 1.2492 - accuracy: 0.2667
Epoch 2/25
120/120 [==============================] - 0s 311us/step - loss: 1.0802 - accuracy: 0.4417
Epoch 3/25
120/120 [==============================] - 0s 289us/step - loss: 1.0455 - accuracy: 0.6250
Epoch 4/25
120/120 [==============================] - 0s 286us/step - loss: 0.9812 - accuracy: 0.6167
Epoch 5/25
120/120 [==============================] - 0s 273us/step - loss: 0.8860 - accuracy: 0.5750
Epoch 6/25
120/120 [==============================] - 0s 283us/step - loss: 0.7844 - accuracy: 0.5667
Epoch 7/25
120/120 [==============================] - 0s 292us/step - loss: 0.6384 - accuracy: 0.6667
Epoch 8/25
120/120 [==============================] - 0s 240us/step - loss: 0.5586 - accuracy: 0.6500
Epoch 9/25
120/120 [==============================] - 0s 254us/step - loss: 0.5125 - accuracy: 0.6667
Epoch 10/25
120/120 [==============================] - 0s 272us/step - loss: 0.4896

Met `model_evaluate` kunnen we bepalen hoe goed het model werkt op de test data.

In [9]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(test_acc)

30/30 [==============================] - 0s 1ms/step
0.8666666746139526


Experimenteer met bovenstaand model. Wat gebeurt er als je meer lagen toevoegt of een laag weghaalt of het aantal neuronen in een laag verandert? 

Probeer ook eens andere activatiefuncties dan `relu`, zoals `tanh` of `sigmoid`.

Welke invloed heeft het aantal epochs?

In [10]:
# bijvoorbeeld (voor een flink slechter resultaat)
model = Sequential()

model.add(Dense(10, input_shape = (4,), activation = 'relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(3, activation = 'sigmoid'))


model.compile(Adam(lr=0.01),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(X_train, y_train, epochs = 25, batch_size = 5)

test_loss, test_acc = model.evaluate(X_test, y_test)
print(test_acc)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/25
120/120 [==============================] - 0s 1ms/step - loss: 0.9864 - accuracy: 0.4833
Epoch 2/25
120/120 [==============================] - 0s 356us/step - loss: 0.6851 - accuracy: 0.6583
Epoch 3/25
120/120 [==============================] - 0s 317us/step - loss: 0.4680 - accuracy: 0.6750
Epoch 4/25
120/120 [==============================] - 0s 294us/step - loss: 0.3882 - accuracy: 0.6750
Epoch 5/25
120/120 [==============================] - 0s 333us/step - loss: 0.3470 - accuracy: 0.6750
Epoch 6/25
120/120 [==============================] - 0s 311us/step - loss: 0.3539 - accuracy: 0.6750
Epoch 7/25
120/120 [==============================] - 0s 296us/step - loss: 0.3234 - accuracy: 0.6750
Epoch 8/25
120/120 [==============================] - 0s 292us/step - loss: 0.2983 - accuracy: 0.6750
Epoch 9/25
120/120 [==============================] - 0s 306us/step - loss: 0.3075 - accurac

We kunnen dezelfde aanpak gebruiken voor andere data, bijvoorbeeld voor het herkennen van cijfers. We gebruiken de MNist dataset die bestaat uit plaatjes van cijfers. Ieder plaatje bestaat uit 28 x 28 pixels.

In [12]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

import warnings
warnings.filterwarnings('ignore')

In [13]:
train_images.shape

(60000, 28, 28)

In [14]:
len(train_labels)

60000

In [15]:
print(train_labels)

[5 0 4 ... 5 6 8]


Een eenvoudig neuraal netwerk heeft een array van input waarden nodig i.p.v. een 2D afbeelding.
We maken van de inputs (waarden tussen 0 en 255) getallen tussen 0 en 1.

In [16]:
train_images = train_images.reshape((60000, 28 * 28)) # lijst van waarden i.p.v. 2D afbeelding
train_images = train_images.astype('float32') / 255 # getallen tussen 0 en 1

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

Voor elk cijfer in de input data maken we een array met 10 waarden, 9 nullen en een één, waarbij de positie van de één aangeeft om welk cijfer het gaat (One hot encoding)

In [17]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


Maak nu een neuraal netwerk met twee lagen, een eerste laag met 512 neuronen en een output laag met 10 neuronen. Geef bij de eerste laag aan hoeveel inputs er zijn en wat de activatiefunctie is. De output laag heeft een `softmax` activatiefunctie.

In [18]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape= (28 * 28, )))
network.add(layers.Dense(10, activation = 'softmax'))

compileer het netwerk.

In [19]:
network.compile(optimizer = 'rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])

train het netwerk 5 epochs met een batch_size van 128.

In [20]:
network.fit(train_images, train_labels, epochs = 5, batch_size = 128)

Epoch 1/5
60000/60000 [==============================] - 2s 34us/step - loss: 0.2538 - accuracy: 0.9269
Epoch 2/5
60000/60000 [==============================] - 2s 34us/step - loss: 0.1042 - accuracy: 0.9690
Epoch 3/5
60000/60000 [==============================] - 2s 38us/step - loss: 0.0678 - accuracy: 0.9792
Epoch 4/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.0495 - accuracy: 0.9851
Epoch 5/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.0377 - accuracy: 0.9890


Evalueer het netwerk op de test set.

In [21]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print(test_acc)

10000/10000 [==============================] - 0s 33us/step
0.9796000123023987


Experimenteer met verschillende netwerken. Varieer het aantal lagen, het aantal neuronen, de activatiefunties en het aantal epochs.

In [22]:
network = models.Sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape= (28 * 28, )))
network.add(layers.Dense(256, activation = 'softmax'))
network.add(layers.Dense(10, activation = 'softmax'))

network.compile(optimizer = 'rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])

network.fit(train_images, train_labels, epochs = 5, batch_size = 128)

Epoch 1/5
60000/60000 [==============================] - 3s 48us/step - loss: 1.8908 - accuracy: 0.6499
Epoch 2/5
60000/60000 [==============================] - 3s 49us/step - loss: 1.3342 - accuracy: 0.6862
Epoch 3/5
60000/60000 [==============================] - 3s 43us/step - loss: 0.9417 - accuracy: 0.6933
Epoch 4/5
60000/60000 [==============================] - 3s 43us/step - loss: 0.7109 - accuracy: 0.6988
Epoch 5/5
60000/60000 [==============================] - 3s 44us/step - loss: 0.5910 - accuracy: 0.7039


In [23]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print(test_acc)

10000/10000 [==============================] - 0s 44us/step
0.7003999948501587


In [24]:
network = models.Sequential()
network.add(layers.Dense(256, activation = 'relu', input_shape= (28 * 28, )))
network.add(layers.Dense(10, activation = 'softmax'))

network.compile(optimizer = 'rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])

network.fit(train_images, train_labels, epochs = 7, batch_size = 100)

Epoch 1/7
60000/60000 [==============================] - 2s 30us/step - loss: 0.2751 - accuracy: 0.9226
Epoch 2/7
60000/60000 [==============================] - 2s 28us/step - loss: 0.1197 - accuracy: 0.9650
Epoch 3/7
60000/60000 [==============================] - 2s 29us/step - loss: 0.0815 - accuracy: 0.9765
Epoch 4/7
60000/60000 [==============================] - 2s 27us/step - loss: 0.0612 - accuracy: 0.9822
Epoch 5/7
60000/60000 [==============================] - 2s 26us/step - loss: 0.0488 - accuracy: 0.9858
Epoch 6/7
60000/60000 [==============================] - 2s 27us/step - loss: 0.0386 - accuracy: 0.9883
Epoch 7/7
60000/60000 [==============================] - 2s 27us/step - loss: 0.0316 - accuracy: 0.9904


In [25]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print(test_acc)

10000/10000 [==============================] - 0s 34us/step
0.9764000177383423
